spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.129:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath:/mapper/pms/*.xml

server:
  port: 10000

